name: edd_playgroud
description: Where one can play around with Flutter and Dart.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/clave_click.wav

  uses-material-design: true
