name: edd_playgroud
description: Where one can play around with Flutter and Dart.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_midi: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/sounds/Steinway+Grand+Piano+ER3A.sf2

  fonts:
    - family: whole
      fonts:
        - asset: assets/fonts/ic_whole.ttf
    - family: half
      fonts:
        - asset: assets/fonts/ic_half.ttf
    - family: quarter
      fonts:
        - asset: assets/fonts/ic_quarter.ttf
    - family: eighth
      fonts:
        - asset: assets/fonts/ic_eighth.ttf
    - family: sixteenth
      fonts:
        - asset: assets/fonts/ic_sixteenth.ttf

